# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: cryptpi/todo-app:PLACEHOLDER_IMAGE
          imagePullPolicy: IfNotPresent
          # ensure SQLite writes under the mounted volume
          env:
            - name: DATABASE
              value: /app/data/todo.db
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: todo-db-storage
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: todo-db-storage
          persistentVolumeClaim:
            claimName: todo-db-pvc